name: CI

on: [push]

jobs:
  tests:
    name: Run Python Unittests
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_FOR_COMPOSE: DockerfileRunTests
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: pip install Cython
    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: docker-compose up --build -d
    - run: sleep 30s
    - run: python unittests.py 